# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:1.19.5

stages:
  - test
  - build

tests:
  stage: test
  script:
    - go test -timeout 30s ./... -coverprofile=coverage.out
    - go tool cover -func=coverage.out   
  artifacts:
    paths:
      - coverage.out
    expire_in: 1 day

spellcheck:
  stage: test
  image: node:19-alpine3.15
  script: 
    - npm i -g cspell-cli
    - npm install -g @cspell/dict-ru_ru
    - cspell-cli -u -c cspell.json "**"
  except:
    - tags

build:
  stage: build
  script:
    - env GOOS=linux go build -o builds/linux -ldflags "-X main.ver=$CI_COMMIT_REF_NAME"
    - env GOOS=darwin go build -o builds/mac.app -ldflags "-X main.ver=$CI_COMMIT_REF_NAME"
  artifacts:
    paths:
      - builds
